import { CareInfoProps, Link, SectionProps } from '../interfaces/Props';
import { clickBtn, content, footerInfo } from '../local/en/section-curves/constants';

const imageInfo = {
    srcOne: 'https://awue1-s3-de-oam-cms-assets-prod-prod-001.s3.amazonaws.com/s3fs-public/2022-05/amazon_lady2_1.png',
    srcTwo: 'https://d38suhqqynrvtl.cloudfront.net/images/photos/ls_computer_O_02.png',
    srcThree: 'https://d38suhqqynrvtl.cloudfront.net/images/photos/ls_livingroom_05.jpg',
    srcFour: 'https://awue1-s3-de-oam-cms-assets-prod-prod-001.s3.amazonaws.com/s3fs-public/2023-02/amazon-hero.png',
    srcFive: 'https://s3.amazonaws.com/upload.uxpin/files/912828/903124/family-v2-9aeeda.png',
    srcSix: 'https://d38suhqqynrvtl.cloudfront.net/images/photos/pr_echo_home_white.png',
};

export const sectionCurveData: SectionProps[] = [
    {
        sectionClassName: 'bg--secondary-light-1 bg-btm-curv bg-animated-curv-blue',
        imgDivClassName: 'col--md-odd-1-push position-swap',
        imgSrc: imageInfo.srcOne,
        imgAlt: content.altOne,
        imgClassName: 'img-fluid mx-auto w-auto',
        title: content.titleOne,
        content: content.descOne,
        btnPrimary: clickBtn,
    },
    {
        sectionClassName: 'bg--secondary-light-1 bg-btm-curv bg-animated-curv-orange',
        contentDivClassName: 'col--md-odd-1-push',
        imgSrc: imageInfo.srcTwo,
        imgAlt: content.altTwo,
        imgClassName: 'img-fluid',
        title: content.titleTwo,
        content: content.descTwo,
        btnSecondary: clickBtn,
    },
    {
        sectionClassName: 'bg--tertiary-base bg-btm-curv',
        imgDivClassName: 'col--md-odd-1-push position-swap',
        imgSrc: imageInfo.srcThree,
        imgAlt: content.altThree,
        imgClassName: 'text-center',
        title: content.titleThree,
        content: content.descTwo,
        btnPrimary: clickBtn,
    },
    {
        sectionClassName: 'bg--tertiary-base bg-top-curv-reverse',
        contentDivClassName: 'col--md-odd-1-push',
        imgSrc: imageInfo.srcFour,
        imgAlt: content.altFour,
        imgClassName: 'text-img img-fluid mb-0',
        title: content.titleFour,
        content: content.descTwo,
        contentSecond: content.descThree,
    },
    {
        sectionClassName: 'bg--tertiary-base bg-top-curv bg-btm-curv-reverse',
        imgDivClassName: 'col--md-odd-1-push position-swap',
        imgSrc: imageInfo.srcFive,
        imgAlt: content.altFive,
        imgClassName: 'img-fluid',
        title: content.titleFive,
        content: content.descTwo,
        btnPrimary: clickBtn,
    },
    {
        sectionClassName: 'bg--tertiary-base bg-btm-curv-reverse',
        contentDivClassName: 'col--md-odd-1-push',
        imgSrc: imageInfo.srcSix,
        imgAlt: content.altSix,
        imgClassName: 'img-fluid',
        title: content.titleSix,
        content: content.descFour,
        btnPrimary: clickBtn,
    },
    {
        sectionClassName: 'bg--tertiary-base bg-top-curv',
        imgDivClassName: 'col--md-odd-1-push position-swap',
        imgSrc: imageInfo.srcThree,
        imgAlt: content.altThree,
        imgClassName: 'text-center img-fluid',
        title: content.titleSeven,
        content: content.descTwo,
        contentSecond: content.descThree,
    },
    {
        sectionClassName: 'bg--primary-light-1 bg-btm-curv',
        imgDivClassName: 'col--md-odd-1-push position-swap',
        imgSrc: imageInfo.srcThree,
        imgAlt: content.altThree,
        imgClassName: 'text-center',
        title: content.titleEight,
        content: content.descTwo,
        btnPrimary: clickBtn,
    },
    {
        sectionClassName: 'bg--primary-light-1 bg-top-curv-reverse',
        contentDivClassName: 'col--md-odd-1-push',
        imgSrc: imageInfo.srcFour,
        imgAlt: content.altFour,
        imgClassName: 'text-img img-fluid mb-0',
        title: content.titleNine,
        content: content.descTwo,
        contentSecond: content.descThree,
    },
    {
        sectionClassName: 'bg--primary-light-1 bg-top-curv bg-btm-curv-reverse',
        imgDivClassName: 'col--md-odd-1-push position-swap',
        imgSrc: imageInfo.srcFive,
        imgAlt: content.altFive,
        imgClassName: 'img-fluid',
        title: content.titleTen,
        content: content.descTwo,
        btnPrimary: clickBtn,
    },
    {
        sectionClassName: 'bg--primary-light-1 bg-btm-curv-reverse',
        imgDivClassName: 'col--md-odd-1-push position-swap',
        imgSrc: imageInfo.srcSix,
        imgAlt: content.altSix,
        imgClassName: 'img-fluid',
        title: content.titleEleven,
        content: content.descFour,
        btnPrimary: clickBtn,
    },
    {
        sectionClassName: 'bg--primary-light-1 bg-top-curv',
        imgDivClassName: 'col--md-odd-1-push position-swap',
        imgSrc: imageInfo.srcThree,
        imgAlt: content.altThree,
        imgClassName: 'text-center img-fluid',
        title: content.titleTwelve,
        content: content.descTwo,
        contentSecond: content.descThree,
    },
    {
        sectionClassName: 'bg--secondary-light-1 bg-btm-curv',
        imgDivClassName: 'col--md-odd-1-push position-swap',
        imgSrc: imageInfo.srcThree,
        imgAlt: content.altThree,
        imgClassName: 'text-center',
        title: content.titleThirteen,
        content: content.descTwo,
        btnPrimary: clickBtn,
    },
    {
        sectionClassName: 'bg--secondary-light-1 bg-top-curv-reverse',
        contentDivClassName: 'col--md-odd-1-push',
        imgSrc: imageInfo.srcFour,
        imgAlt: content.altFour,
        imgClassName: 'text-img img-fluid mb-0',
        title: content.titleFourteen,
        content: content.descTwo,
        contentSecond: content.descThree,
    },
    {
        sectionClassName: 'bg--secondary-light-1 bg-top-curv bg-btm-curv-reverse',
        imgDivClassName: 'col--md-odd-1-push position-swap',
        imgSrc: imageInfo.srcFive,
        imgAlt: content.altFive,
        imgClassName: 'img-fluid',
        title: content.titleFifteen,
        content: content.descTwo,
        btnPrimary: clickBtn,
    },
    {
        sectionClassName: 'bg--secondary-light-1 bg-btm-curv-reverse',
        contentDivClassName: 'col--md-odd-1-push',
        imgSrc: imageInfo.srcSix,
        imgAlt: content.altSix,
        imgClassName: 'img-fluid',
        title: content.titleSixteen,
        content: content.descFour,
        btnPrimary: clickBtn,
    },
    {
        sectionClassName: 'bg--secondary-light-1 bg-top-curv',
        imgDivClassName: 'col--md-odd-1-push position-swap',
        imgSrc: imageInfo.srcThree,
        imgAlt: content.altThree,
        imgClassName: 'text-center img-fluid',
        title: content.titleSeventeen,
        content: content.descTwo,
        contentSecond: content.descThree,
    },
];

export const CustomerCareData: CareInfoProps[] = [
    {
        title: footerInfo.titleOne,
        phoneNumber: '1-855-936-6417',
        hours: `${footerInfo.hour}: 7:00am-8:00pm ${footerInfo.date}`,
    },
    {
        title: footerInfo.titleTwo,
        phoneNumber: '1-855-936-6417',
        hours: `${footerInfo.hour}: 7:00am-8:00pm ${footerInfo.date}`,
    },
    { title: footerInfo.titleThree, loginlink: 'http://www.useit.com', newUserLink: '#' },
];

export const links: Link[] = [
    {
        title: footerInfo.linkTitleOne,
        url: 'https://www.directenergy.com/terms-of-use',
    },
    {
        title: footerInfo.linkTitleTwo,
        url: 'https://www.directenergy.com/text-messages-faqs/sms-terms-and-conditions',
    },
    {
        title: footerInfo.linkTitleThree,
        url: 'https://www.directenergy.com/privacy-policy',
    },
    {
        title: footerInfo.linkTitleFour,
        url: 'https://www.directenergy.com/learning-center',
    },
    {
        title: footerInfo.linkTitleFive,
        url: 'https://www.directenergy.com/sitemap',
    },
];
